apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: NodePort
  selector:
    app: backend
  ports:
  - port: 3800
    nodePort: 30800
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: mereyes21/my-moneybox-api:0.0.2
        env:
          - name: POSTGRE_PASS
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: password
          - name: POSTGRE_HOST
            value: postgres
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 3800