apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: back-app
  template:
    metadata:
      labels:
        app: back-app
    spec:
      containers:
      - name: back-app
        image: porfixlp/budget-app-api:01
        env:
          - name: POSTGRES_PASS
            valueFrom:
              secretKeyRef:
                name: pg-secrets-ag
                key: password
          - name: POSTGRES_HOST
            value: pg-service
        resources:
          limits:
            memory: "256Mi"
            cpu: "256m"
        ports:
        - containerPort: 3800
---
apiVersion: v1
kind: Service
metadata:
  name: back-service
spec:
  type: LoadBalancer
  selector:
    app: back-app
  ports:
  - port: 3800
    targetPort: 3800