-- DROP TABLE PERSON;
-- DROP TABLE CATEGORY;

-- PERSON CREATION
CREATE TABLE PERSON (
	PERSON SERIAL PRIMARY KEY,
	EMAIL TEXT UNIQUE NOT NULL,
	PASSWORD TEXT NOT NULL,
	PERSON_TOKEN TEXT NOT NULL,
	FIRST_NAME TEXT NOT NULL,
	LAST_NAME TEXT NOT NULL,
	ADD_DATE DATE DEFAULT CURRENT_TIMESTAMP,
	MOD_DATE DATE
);

-- CATEGORY CREATION
CREATE TABLE CATEGORY (
	CATEGORY SERIAL PRIMARY KEY,
	PERSON SERIAL NOT NULL REFERENCES PERSON(PERSON),
	NAME TEXT NOT NULL,
	DESCRIPTION TEXT NOT NULL,
	ADD_DATE DATE DEFAULT CURRENT_TIMESTAMP,
	MOD_DATE DATE
);

-- CREATE FUNCTION
CREATE OR REPLACE FUNCTION API_TOKEN (PSECRET TEXT) 
    RETURNS SETOF TEXT 
AS $$
BEGIN
    RETURN QUERY SELECT MD5(PSECRET);
END; $$ 

LANGUAGE 'plpgsql';
